import Head from 'next/head'
import Image from 'next/image'

export default function ColorsBeginner() {
  return (
    <div>
      <Head>
        <title>ESL Universe! English Teaching</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="bg-heroimage h-full min-h-screen bg-cover bg-right">
          <div className="bg-violet-900 bg-opacity-60 h-full min-h-screen w-screen text-center p-12 xl:p-20">
            <div className="flex flex-col justify-center items-center max-w-full">
              <h1 className="text-4xl md:text-6xl xl:text-9xl font-bold text-violet-200 p-6">Colors</h1>
              <h2 className="text-2xl md:text-3xl xl:text-4xl font-bold text-violet-200 p-2">颜色</h2>
              <div className="flex flex-row flex-wrap justify-center p-2 m-2">
                
                <div className="flex flex-row flex-wrap justify-center content-center max-w-2xl p-2 m-2">
                    <div className="bg-white bg-opacity-80 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-900 font-bold text-xl md:text-2xl lg:text-4xl p-2">White</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">白色</h3>
                    </div>
                    <div className="bg-black bg-opacity-80 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl lg:text-4xl p-2">Black</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">黑色</h3>
                    </div>
                    <div className="bg-gray-900 bg-opacity-90 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl lg:text-4xl p-2">Gray</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">灰色</h3>
                    </div>
                    <div className="bg-red-900 bg-opacity-90 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl lg:text-4xl p-2">Red</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">红色</h3>
                    </div>
                    <div className="bg-blue-900 bg-opacity-90 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl lg:text-4xl p-2">Blue</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">蓝色</h3>
                    </div>
                    <div className="bg-yellow-600 bg-opacity-90 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl lg:text-4xl p-2">Yellow</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">黄色</h3>
                    </div>
                    <div className="bg-green-900 bg-opacity-90 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl lg:text-4xl p-2">Green</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">绿色</h3>
                    </div>
                    <div className="bg-purple-900 bg-opacity-90 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl lg:text-4xl p-2">Purple</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">紫色</h3>
                    </div>
                    <div className="bg-orange-600 bg-opacity-90 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl lg:text-4xl p-2">Orange</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">橙色</h3>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

    </div>
  )
}
