import Head from 'next/head'
import Image from 'next/image'

export default function CalendarBeginner() {
  return (
    <div>
      <Head>
        <title>ESL Universe! English Teaching</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="bg-heroimage h-full min-h-screen bg-cover bg-right">
          <div className="bg-violet-900 bg-opacity-60 h-full min-h-screen w-screen text-center p-12 xl:p-20">
            <div className="flex flex-col justify-center items-center max-w-full">
              <h1 className="text-4xl md:text-6xl xl:text-9xl font-bold text-violet-200 p-6">The Calendar</h1>
              <h2 className="text-2xl md:text-3xl xl:text-4xl font-bold text-violet-200 p-2">日历</h2>

              <div className="flex flex-row flex-wrap justify-center p-2 m-2">
                <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                  <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">Day</h2>
                  <h3 className="text-violet-300 text-xl md:text-2xl p-2">日</h3>
                </div>
                <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                  <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">Month</h2>
                  <h3 className="text-violet-300 text-xl md:text-2xl p-2">月</h3>
                </div>
                <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                  <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">Year</h2>
                  <h3 className="text-violet-300 text-xl md:text-2xl p-2">年</h3>
                </div>
              </div>




              <div className="flex flex-col flex-wrap justify-center p-2 m-2">
                
                <h2 className="text-xl lg:text-2xl font-bold text-violet-200">The Week (星期)</h2>
                <div className="flex flex-row flex-wrap justify-center max-w-2xl p-2 m-2">
                  
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">Monday</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">星期一</h3>
                    </div>
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">Tuesday</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">星期二</h3>
                    </div>
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">Wednesday</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">星期三</h3>
                    </div>
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">Thursday</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">星期四</h3>
                    </div>
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">Friday</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">星期五</h3>
                    </div>
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">Saturday</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">星期六</h3>
                    </div>
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">Sunday</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">星期日</h3>
                    </div>
                </div>
                                
                <h2 className="text-xl lg:text-2xl font-bold text-violet-200">The Months (月份)</h2>
                <div className="flex flex-row flex-wrap justify-center max-w-2xl p-2 m-2">
                  
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">January</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">一月</h3>
                    </div>
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">February</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">二月</h3>
                    </div>
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">March</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">行进</h3>
                    </div>
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">April</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">四月</h3>
                    </div>
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">May</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">可能</h3>
                    </div>
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">June</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">星期六</h3>
                    </div>
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">July</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">星期日</h3>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

    </div>
  )
}
