import Head from 'next/head'
import Image from 'next/image'

export default function NumbersBeginner() {
  return (
    <div>
      <Head>
        <title>ESL Universe! English Teaching</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="bg-heroimage h-full min-h-screen bg-cover bg-right">
          <div className="bg-violet-900 bg-opacity-60 h-full min-h-screen w-screen text-center p-12 xl:p-20">
            <div className="flex flex-col justify-center items-center max-w-full">
              <h1 className="text-4xl md:text-6xl xl:text-9xl font-bold text-violet-200 p-6">Numbers</h1>
              <h2 className="text-2xl md:text-3xl xl:text-4xl font-bold text-violet-200 p-2">数字</h2>
              <div className="flex flex-row flex-wrap justify-center p-2 m-2">
                
                <div className="flex flex-row flex-wrap justify-center max-w-2xl p-2 m-2">
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">0</h2>
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">Zero</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">〇</h3>
                    </div>
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">1</h2>
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">One</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">一</h3>
                    </div>
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">2</h2>
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">Two</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">二</h3>
                    </div>
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">3</h2>
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">Three</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">三</h3>
                    </div>
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">4</h2>
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">Four</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">四</h3>
                    </div>
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                      <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">5</h2>
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">Five</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">五</h3>
                    </div>
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">6</h2>
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">Six</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">六</h3>
                    </div>
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                      <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">7</h2>
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">Seven</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">七</h3>
                    </div>
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">8</h2>
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">Eight</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">八</h3>
                    </div>
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">9</h2>
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">Nine</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">九</h3>
                    </div>
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">10</h2>
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">Ten</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">十</h3>
                    </div>
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">100</h2>
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">One Hundred</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">百</h3>
                    </div>
                    <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-4 m-2 text-violet-300">
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">1,000</h2>
                        <h2 className="text-violet-300 font-bold text-xl md:text-2xl p-2">One Thousand</h2>
                        <h3 className="text-violet-300 text-xl md:text-2xl p-2">千</h3>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

    </div>
  )
}
