import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Jingles from '../public/jingles.png'

export default function Home() {
  return (
    <div>
      <Head>
        <title>ESL Universe! English Teaching</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="bg-heroimage h-90vh bg-cover bg-right">
          <div className="bg-violet-900 bg-opacity-60 h-90vh w-screen text-center p-12">
            <div className="flex flex-col justify-center items-center max-h-70vh max-w-lg xl:max-w-full p-12 m-6">
              <div className="font-bold text-violet-200 p-2 m-4">
                <h1 className="text-4xl md:text-4xl xl:text-6xl font-bold text-violet-200 p-2">Online English Classes</h1>
                <h2 className="text-2xl md:text-3xl xl:text-4xl font-bold text-violet-200 p-2">在线英语学习</h2>
              </div>
              <div className="flex flex-row flex-wrap justify-center p-2 max-h-70vh">
                <Link href="/beginner">
                  <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-6 xl:p-12 m-2 text-violet-300">
                    <h2 className="text-violet-300 font-bold text-xl lg:text-2xl p-2">Beginner</h2>
                    <h3 className="text-violet-300 text-xl md:text-2xl p-2">低级</h3>
                    <p className="text-violet-300 opacity-60 p-2">Colors - Numbers </p>
                    <p className="text-violet-300 opacity-60 p-2">颜色 - 数字 </p>
                  </div>
                </Link>
                <Link href="/intermediate">
                  <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-6 xl:p-12 m-2">
                    <h2 className="text-violet-300 font-bold text-xl lg:text-2xl p-2">Intermediate</h2>
                    <h3 className="text-violet-300 text-xl md:text-2xl p-2">中级</h3>
                    <h3 className="text-violet-300 opacity-60">CEFR Level B1 - B2</h3>
                  </div>                  
                </Link>
                <Link href="/advanced">
                  <div className="bg-violet-300 bg-opacity-20 hover:bg-opacity-30 transition-all rounded-xl p-6 xl:p-12 m-2">
                    <h2 className="text-violet-300 font-bold text-xl lg:text-2xl p-2">Advanced</h2>
                    <h3 className="text-violet-300 text-xl md:text-2xl p-2">高级</h3>
                    <h3 className="text-violet-300 opacity-60">CEFR Level C1 - C2</h3>
                  </div>
                </Link>
              </div>
              <Link href="/classes">
                <button className="max-w-fit bg-violet-300 text-purple-900 font-bold p-6 m-2 text-xl lg:text-2xl rounded-xl bg-opacity-90 hover:drop-shadow-2xl transition-all">Learn More</button>
              </Link>
            </div>
          </div>
        </div>
        <div className="flex flex-col justify-center content-center items-center bg-gradient-to-bl from-violet-800 to-purple-900 text-violet-300 p-4">
          <h1 className="text-center font-bold p-4 text-xl lg:text-2xl xl:text-4xl text-violet-200">About Mrs. A</h1>
          <button className="max-w-fit bg-violet-300 text-purple-900 font-bold p-6 m-2 text-xl lg:text-2xl rounded-xl bg-opacity-90 hover:drop-shadow-2xl transition-all">Book a Class</button>
          <div className="flex flex-row flex-wrap justify-center content-center items-center text-center">
            <div className="max-w-xl p-4 m-2">
              <p className="text-center font-bold p-2 text-md lg:text-lg">Mrs. A is an English teacher with five years of experience teaching English as a foreign language to K-12 students.  She holds a Bachelor of Arts degree from the University of Texas at Austin and a certification in TESOL (Teaching English to Speakers of Other Languages).</p>
              <p className="text-center font-bold p-2 text-md lg:text-lg">When not tutoring, she substitute teaches in a public elementary school in which 42% of the student body speaks English as a second language.</p>
              <p className="text-center font-bold p-2 text-md lg:text-lg">Her pet cat is named Mr. Jingles.</p>
            </div>
            <div className=" p-4 m-2">
              <Image src={Jingles} height={300} width={300} className="bg-violet-900 bg-opacity-90 rounded-full z-1"/>
            </div>
          </div>
        </div>
      </main>

    </div>
  )
}
