import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export default function Profile() {
  return (
    <div>
      <Head>
        <title>ESL Universe! English Teaching</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="bg-heroimage h-full min-h-screen bg-cover bg-right">
          <div className="bg-violet-900 bg-opacity-60 h-full min-h-screen w-screen text-center p-12 xl:p-20">
            <div className="flex flex-col justify-center items-center max-w-full">
              <h1 className="text-4xl md:text-6xl xl:text-9xl font-bold text-violet-200 p-6">My Page</h1>
              <h2 className="text-2xl md:text-3xl xl:text-4xl font-bold text-violet-200 p-2">在线的用户配置文件</h2>
            </div>
            <div className="flex flex-col flex-wrap justify-center items-center">
              <p className="bg-violet-300 p-2 m-2 rounded-xl max-w-fit text-xl opacity-80 hover:opacity-100">My Classes</p>
            </div>
          </div>
        </div>
      </main>

    </div>
  )
}
